###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

[mqtt]
host = 'localhost'
port = 1883
wsPort = 8880

[nats]
host = 'localhost'
port = 4222
